### ISSUE TITLE
Non working buttons

### ISSUE THREAD

**Issue by OhCirca** [mintunmedia/groups-for-membermouse#1]
None of the available buttons seem to be working, create group type, need help.

**Comment by vramiguez** [comment]
I had the same problem and found that the issue was the name of the unzipped folder. After renaming the folder from membermouse-groups-addon-master to MemberMouseGroupAddon the plugin and its buttons started to work fine. 

Already added a pull request with the Read Me file, and waiting for the plugin owner to approve it. 

Hope this work for you too.

**Comment by raleighwood** [comment]
I'm having the same issue and the folder name change doesn't seem to resolve it. Any thoughts from the MM community? The top-level navigation buttons work, but the green buttons to create groups don't. I'm thinking this is isolated to javascript...

**Comment by roymckenzie** [comment]
@raleighwood this should be working once you rename the folder. If you think it is related to JavaScript, could you try opening up your browser console to see if there is any error that gets logged? Thanks!
