### ISSUE TITLE
Group Sign-Up Link Not Working

### ISSUE THREAD

**Issue by blaksheep85** [mintunmedia/groups-for-membermouse#16]
I had groups set up on my staging server and everything was working perfectly. I had to move the database over to the live site manually because it's on a multisite and we couldn't overwrite other subsites. Anyway, for some reason, now that the database has been moved and we set up MemberMouse and groups again, the [MM_Group_SignUp_Link] sortcode is not working or showing anything and if I use a purchase code generated from one of my groups, it's not discounting the membership (I have the add-on set to be free). I'm thinking there must be something in the database that is not matched up to the live site hindering this from working, but we haven't been able to figure it out. Any insight would be greatly appreciated.

For what it's worth, I have uninstalled an re-installed the plugin. It fixed a couple of bugs we had at firs, but not this one.

Thanks!
Gabe

**Comment by mattmintun** [comment]
Hey there Gabe! I'll have one of my developers take a look and see what we can find. For what it's worth, we're still working on getting this plugin fully running again and plan on having a new release within the coming weeks that should fix all of the issues thus far since taking it over from MemberMouse.

**Comment by raleighwood** [comment]
Very excited about all the updates I saw today - looking forward to installing and running with it! Thanks in advance, Matt!
